[package]
name = "Eternal"
description = "A modern terminal developed using Rust. / 使用Rust开发的现代终端。"
repository = "https://github.com/Binder-organize/Eternal"
authors = [
    "Gavin Zheng <gav.zheng@outlook.com>",
    "Cheple Bob <Cheple_Bob@outlook.com>",
]
license = "MIT"
readme = "README.md"
keywords = ["terminal", "rust"]
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "^0.30.0"
eframe = "^0.30.0"
egui_extras = { version = "^0.30.0", features = ["all_loaders"] }
rodio = "^0.20.1"
hound = "^3.5.1"
anyhow = "^1.0.95"
screen_size = "^0.1.0"
image = "^0.25.5"